services:
    ArturDoruch\EventLoggerBundle\EventLogger:
        alias: arturdoruch_eventlogger.event_logger
        public: false

    arturdoruch_eventlogger.event_logger:
        class: ArturDoruch\EventLoggerBundle\EventLogger
        arguments: ['@arturdoruch_eventlogger.log_metadata']

    arturdoruch_eventlogger.event_processor.exception_processor:
        class: ArturDoruch\EventLoggerBundle\EventProcessor\ExceptionProcessor

    arturdoruch_eventlogger.database_log_handler:
        class: ArturDoruch\EventLoggerBundle\Log\Handler\DatabaseLogHandler
        arguments: ['@arturdoruch_eventlogger.entity_log_manager']
        public: true

    # Log viewing
    arturdoruch_eventlogger.entity_log_manager:
        class: ArturDoruch\EventLoggerBundle\Entity\LogManager
        arguments:
            - '@doctrine'
            - '@arturdoruch_eventlogger.log_property_collection'
            - '%arturdoruch_eventlogger.log.entity_class%'
            - '@twig'

    arturdoruch_eventlogger.database_log_driver:
        class: ArturDoruch\EventLoggerBundle\Log\Driver\DatabaseLogDriver
        arguments:
            - '@arturdoruch_eventlogger.entity_log_manager'
            - '@arturdoruch_eventlogger.log_metadata'

    arturdoruch_eventlogger.form.log_filter_type:
        class: ArturDoruch\EventLoggerBundle\Form\LogFilterType
        arguments: ['@arturdoruch_eventlogger.log_property_collection']
        public: false
        tags: ['form.type']

    arturdoruch_eventlogger.twig.misc_extension:
        class: ArturDoruch\EventLoggerBundle\Twig\Extension\MiscExtension
        arguments: ['%arturdoruch_eventlogger.templating.base_template%']
        public: false
        tags: ['twig.extension']

    arturdoruch_eventlogger.twig.log_context_extension:
        class: ArturDoruch\EventLoggerBundle\Twig\Extension\LogContextExtension
        arguments:
            - '@arturdoruch_eventlogger.templating.log_context.object_converter_manager'
            - '@arturdoruch_eventlogger.templating.log_context.value_formatter_manager'
        public: false
        tags: ['twig.extension']

    twig.extension.string:
        class: Twig\Extra\String\StringExtension
        tags: ['twig.extension']

    arturdoruch_eventlogger.controller.log_controller:
        class: ArturDoruch\EventLoggerBundle\Controller\LogController
        arguments:
            - '@arturdoruch_eventlogger.database_log_driver'
            - '@arturdoruch_eventlogger.log_property_collection'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]